# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pankaj/Documents/cg3207/project3207.cache/wt [current_project]
set_property parent.project_path C:/Users/pankaj/Documents/cg3207/project3207.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/pankaj/Documents/cg3207/project3207.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/ALU.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/ARM.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/CondLogic.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/Decoder.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/Extend.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/ProgramCounter.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/RegFile.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/Shifter.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/uart.vhd
  C:/Users/pankaj/Documents/cg3207/project3207.srcs/sources_1/imports/Lab_2_VHDL/TOP.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/pankaj/Documents/cg3207/project3207.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/pankaj/Documents/cg3207/project3207.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc]


synth_design -top TOP -part xc7a100tcsg324-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
